/**
 * Registry: action string (kebab-case) -> handler(ctx)
 * ctx: { req, res, log, error, stripe, databases, users, config, payload }
 */
module.exports = {
  'list-products': require('./list-products'),
  /** WPHub catalog: StripePlan[] */
  list: require('./list'),
  /** Admin plan detail page (`productId`, `plan`, `stats`, `subscribers`) */
  get: require('./get-plan'),
  'get-product': require('./get-product'),
  'create-product': require('./create-product'),
  'list-prices': require('./list-prices'),
  'create-price': require('./create-price'),
  'list-customers': require('./list-customers'),
  'get-customer': require('./get-customer'),
  'update-customer': require('./update-customer'),
  'create-customer': require('./create-customer'),
  'list-invoices': require('./list-invoices'),
  'get-invoice': require('./get-invoice'),
  'get-subscription': require('./get-subscription'),
  'list-subscriptions': require('./list-subscriptions'),
  'create-subscription': require('./create-subscription'),
  'update-subscription': require('./update-subscription'),
  'search-customers': require('./search-customers'),
  'invoice-create-preview': require('./invoice-create-preview'),
  'list-subscription-schedules': require('./list-subscription-schedules'),
  'get-subscription-schedule': require('./get-subscription-schedule'),
  'release-subscription-schedule': require('./release-subscription-schedule'),
  'member-subscription-details': require('./member-subscription-details'),
  'get-price': require('./get-price'),
  'create-portal-session': require('./create-portal-session'),
  'list-payment-methods': require('./list-payment-methods'),
  'create-setup-intent': require('./create-setup-intent'),
  'attach-payment-method': require('./attach-payment-method'),
  'detach-payment-method': require('./detach-payment-method'),
  'set-default-payment-method': require('./set-default-payment-method'),
  'verify-webhook': require('./verify-webhook'),
  'get-publishable-key': require('./get-publishable-key'),
  'admin-list-subscriptions': require('./admin-list-subscriptions'),
  'admin-finance-summary': require('./admin-finance-summary'),
  'admin-finance-dashboard': require('./admin-finance-dashboard'),
  'admin-get-details': require('./admin-get-details'),
  'admin-list-payment-intents': require('./admin-list-payment-intents'),
  'admin-get-payment-intent': require('./admin-get-payment-intent'),
  'admin-cancel-subscription': require('./admin-cancel-subscription'),
  'admin-pause-subscription': require('./admin-pause-subscription'),
  'admin-resume-subscription': require('./admin-resume-subscription'),
  'admin-archive-subscription': require('./admin-archive-subscription'),
  'admin-update-subscription-price': require('./admin-update-subscription-price'),
  'order-payments-checkout': require('./order-payments-checkout'),
  'admin-delete-plan': require('./admin-delete-plan'),
};
